# Added by SF

copy: copy.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o copy copy.c -lm

whodunit: whodunit.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o whodunit whodunit.c -lm

resize: resize.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o resize resize.c -lm